1. Imports

In [5]:
import pandas as pd
import os

print("Working directory:", os.getcwd())

Working directory: /Users/tharungopinath/Desktop/Future Interns/sales-demand-forecasting/notebooks

2. Load Data

In [6]:
DATA_PATH = "../data/raw/train.csv"
df = pd.read_csv(DATA_PATH)

df.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

3. Convert Date Column

In [7]:
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date")
print("Date range:", df["date"].min(), "to", df["date"].max())

Date range: 2013-01-01 00:00:00 to 2017-08-15 00:00:00

4. Basic Inspection

In [8]:
print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nMissing Values:\n", df.isnull().sum())
print("\nData Types:\n", df.dtypes)

df.head()

Shape: (3000888, 6)

Columns:
 Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion'], dtype='str')

Missing Values:
 id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

Data Types:
 id                      int64
date           datetime64[us]
store_nbr               int64
family                    str
sales                 float64
onpromotion             int64
dtype: object

        id       date  store_nbr        family  sales  onpromotion
0        0 2013-01-01          1    AUTOMOTIVE    0.0            0
1194  1194 2013-01-01         42   CELEBRATION    0.0            0
1193  1193 2013-01-01         42  BREAD/BAKERY    0.0            0
1192  1192 2013-01-01         42         BOOKS    0.0            0
1191  1191 2013-01-01         42     BEVERAGES    0.0            0

## 📌 Summary

- Loaded raw sales dataset from `data/raw/train.csv`
- Converted `date` column to datetime format
- Inspected dataset structure (shape, columns, data types, missing values)
- Displayed descriptive statistics

### 🎯 Purpose
Understand the raw data before any processing or aggregation.